title: bean blog
theme: minima
author: ranu baidya
email: nunya@business.com
description: bean consumption blog
  beans

# social links
twitter_username: beans # DO NOT include the @ character, or else the build will fail!
github_username:  beans # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
